source 'https://rubygems.org'

gem 'rake'
# Add your dependencies here:
gem 'motion-cocoapods',  github: 'HipByte/motion-cocoapods'
gem 'ProMotion',         github: 'clearsightstudio/ProMotion'
gem 'bubble-wrap',       github: 'rubymotion/BubbleWrap'
gem 'sugarcube',         github: 'rubymotion/sugarcube'
gem 'afmotion',          github: 'usepropeller/afmotion'
gem 'motion-kit',        github: 'rubymotion/motion-kit'
gem 'motion-testflight', github: 'HipByte/motion-testflight'
